### ISSUE TITLE
Add bug report contact details.

### ISSUE THREAD

**Issue by danpalmer** [monzo/docs#60]
As mentioned in the docs, this API is in active development and can change frequently. Coming back to a project for the first time in a few months I found a number of changes in the API that are undocumented, and have found several bugs.

This repository feels like the wrong place to report bugs, so some official documentation on where to report bugs to would be greatly appreciated.

**Comment by obeattie** [comment]
I think this repository is probably the best way to report bugs, at least for the moment 😄
